mutation CreateCampaign($createCampaignInput: CreateCampaignInput!) {
  createCampaign(createCampaignInput: $createCampaignInput) {
    endType
    keyword
    name
    providers
  }
}

mutation UpdateCampaign(
  $id: String!
  $updateCampaignInput: UpdateCampaignInput!
) {
  updateCampaign(id: $id, updateCampaignInput: $updateCampaignInput) {
    endType
    keyword
    name
    providers
  }
}

mutation RemoveCampaign($removeCampaignId: [String!]!) {
  removeCampaign(id: $removeCampaignId)
}

query Campaign($listCampaignInput: ListCampaignInput!) {
  campaign(ListCampaignInput: $listCampaignInput) {
    name
    keyword
    status
    providers
    endType
    endValue
    id
  }

  campaignCount {
    count
  }
}

query CampaignById($campaignByIdId: String!) {
  campaignById(id: $campaignByIdId) {
    id
    name
    keyword
    providers
    createdAt
    updatedAt
    status
    endType
    endValue
  }
}

query CampaignById($id: String!) {
  campaignById(id: $id) {
    name
    keyword
    status
    providers
    endType
    endValue
    id
  }
}
