query Candidates($listCandidateInput: ListCandidateInput!) {
  candidates(listCandidateInput: $listCandidateInput) {
    id
    name
    position
    salary
    yearsOfExperience
    createdAt
  }

  candidatesCount {
    count
  }
}

mutation RemoveCandidate($removeCandidate: [String!]!) {
  removeCandidate(id: $removeCandidate)
}
